# Generated by Django 4.2.7 on 2025-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(help_text='CNPJ da empresa (formato: XX.XXX.XXX/XXXX-XX)', max_length=18, unique=True, verbose_name='CNPJ')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('configuracoes', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do cliente em formato JSON', verbose_name='Configurações')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_empresa'],
            },
        ),
    ]
