# Generated by Django 4.2.7 on 2025-09-12 16:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('tipo', models.CharField(choices=[('analise', 'DEP. Análise'), ('laboratorio', 'DEP. Laboratório'), ('industrial', 'DEP. Industrial'), ('estoque', 'DEP. Estoque'), ('expedicao', 'DEP. Expedição')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantidade')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('data_fabricacao', models.DateField(verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Unitário (R$)')),
                ('status_analise', models.CharField(choices=[('pendente', 'Pendente Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('bloqueado', 'Bloqueado')], default='pendente', max_length=20, verbose_name='Status da Análise')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_ultima_movimentacao', models.DateTimeField(auto_now=True, verbose_name='Última Movimentação')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='inventory.departamento', verbose_name='Departamento Atual')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='Email de Contato')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco_completo', models.TextField(verbose_name='Endereço Completo')),
                ('pessoa_contato', models.CharField(max_length=200, verbose_name='Pessoa de Contato')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, unique=True, verbose_name='Código do Produto')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('L', 'Litro'), ('M', 'Metro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=20, verbose_name='Unidade de Medida')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Unitário (R$)')),
                ('estoque_minimo', models.PositiveIntegerField(default=10, verbose_name='Estoque Mínimo')),
                ('requer_analise', models.BooleanField(default=True, verbose_name='Requer Análise')),
                ('tempo_analise_dias', models.PositiveIntegerField(default=7, verbose_name='Tempo de Análise (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='inventory.categoriaproduto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['codigo_produto'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True, verbose_name='Número da Nota')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processada', 'Processada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='inventory.fornecedor', verbose_name='Fornecedor')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao', '-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste'), ('descarte', 'Descarte')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('motivo', models.TextField(verbose_name='Motivo/Observações')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='inventory.departamento', verbose_name='Departamento de Destino')),
                ('departamento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='inventory.departamento', verbose_name='Departamento de Origem')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventory.estoque', verbose_name='Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventory.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Unitário (R$)')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('data_fabricacao', models.DateField(verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_nota', to='inventory.notafiscal', verbose_name='Nota Fiscal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nota', to='inventory.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal',
                'verbose_name_plural': 'Itens de Nota Fiscal',
                'ordering': ['produto__codigo_produto'],
            },
        ),
        migrations.AddField(
            model_name='estoque',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='inventory.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='inventory.produto', verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='AnaliseQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_analise', models.CharField(max_length=50, unique=True, verbose_name='Número da Análise')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20, verbose_name='Status')),
                ('resultado', models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aprovado_condicional', 'Aprovado Condicional')], max_length=30, null=True, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('laudo_tecnico', models.TextField(blank=True, verbose_name='Laudo Técnico')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises', to='inventory.estoque', verbose_name='Estoque')),
                ('responsavel_analise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Análise')),
            ],
            options={
                'verbose_name': 'Análise de Qualidade',
                'verbose_name_plural': 'Análises de Qualidade',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
